_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "/home/fk1/workspace/OWOD/output/t2_ft_10/model_final.pth"
DATASETS:
  TRAIN: ('t2_voc_coco_2007_ft', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (16000, 19000)  # (122000, 132000)
  MAX_ITER: 21000  # 142000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2_ft"
OWOD:
  PREV_INTRODUCED_CLS: 13  # 20
  CUR_INTRODUCED_CLS: 7  # 20
  ENABLE_CLUSTERING: False
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False
  CLUSTERING:
    START_ITER: 9000  # 90000